name: Build Firmware
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.12.0'
    - name: Build web dist
      working-directory: ./main/http_server/axe-os
      run: |
        npm ci
        npm run build
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.4
        target: esp32s3
        command: GITHUB_ACTIONS="true" idf.py build
        path: '.'
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install esptool
    - name: "Create factory/merged image"
      run: "./merge_bin.sh ./esp-miner-merged.bin"
    - name: upload esp-miner-merged.bin
      uses: actions/upload-artifact@v4
      with:
        name: esp-miner-factory.bin
        path: ./esp-miner-merged.bin
    - name: upload esp-miner.bin
      uses: actions/upload-artifact@v4
      with:
        name: esp-miner.bin
        path: ./build/esp-miner.bin
    - name: upload www.bin
      uses: actions/upload-artifact@v4
      with:
        name: www.bin
        path: ./build/www.bin
